### ISSUE TITLE
Dual DC12v brushed motors not spinning up

### ISSUE THREAD

**Issue by koldogut** [jazzl0ver/ardupilot-rover-l298n#2]
Hello all, a newbie here!

I’ve followed the instructions to set up a Rover with 2 DC 12v brushed motors and no luck. Im using a pixhawk 2.4.8 with Ardurover 4.2.3, (here you are some wiring photos according to specifications; config parameters are also as described in the code section and lua script already loaded), the only difference is that I set up motor A and B as throttle left and right instead of steering and throttle. When I try the motors nothing happens nor actioning the Receiver

![IMG_6364](https://user-images.githubusercontent.com/43078880/212537651-58346026-baab-4e8d-bab3-d682af44605c.jpg)
![IMG_6365](https://user-images.githubusercontent.com/43078880/212537654-0039064f-aff2-4139-af2d-403198fcbc7c.jpg)
![IMG_6366](https://user-images.githubusercontent.com/43078880/212537655-27e630d3-bb73-45ba-9dad-b39303bdc499.jpg)

I’ll appreciate any clue, log or similar to continue investigating the issue or any tip to address the problem.

Thank you in advance.

**Comment by jazzl0ver** [comment]
Hi koldgut. I don't see a GND connection from the Pixhawk output rail to the L298N GND pin. Give it a try.

**Comment by koldogut** [comment]
No luck, I've connected L298N GND with MAIN OUT 2 GND and still no movement from motors; what I've seen in the logs is this message non-stop:  Throttle: 1006, RELAY_IN3: 0, RELAY_IN4: 1

**Comment by jazzl0ver** [comment]
Try to check the following:
1. The most important: there's 5V between IN3 and IN4 and between ENA/ENB and GND on L298N and there's 12V (or whatever your motors consume) on the L298N Vcc input and the motors output. In case you've got no potential difference, it might mean there's something wrong with wiring or with the pixhawk setup. Try to measure on the MAIN/AUX rails directly.
2. PWM values in the script (1530, 1540, 1490, 1500) match your real values

And you may ignore that log messages -they're just for debugging purposes. Also during debugging you may increase the delay from 50ms to, say, 500ms (in function update()).

**Comment by koldogut** [comment]
After a carefull review of your instructions I find out that Min throttle is 60%! Now I'll continue wondering why somewhere else... thank you very much for your support
