### ISSUE TITLE
Throttle Motor moving in only one direction

### ISSUE THREAD

**Issue by SarthakRobotics** [jazzl0ver/ardupilot-rover-l298n#3]
i have made the exact connections and parameters but the my throttle motor would move in only one direction desipite of moving the throttle stick front and back.
In Servo Motor tab the throttle stick goes from 1100 to higher when i move the stick in foward direction and the same happens if i move the stick backward. (the movement of throttle in servo tab only happens in when the rover is armed)

In case of GroundSteering(not -armed) the servo tab is at 1500 when center stick position goes to 1100 when i move the stick right and goes to 1900 when i move the stick left ( But when the rover is armed it just goes from 1500 to 1900 when i move the stick either ways right or left)

when armed the motor attached to ground steering IN AND EN the motor move in both direction but the Throttle Motors goes only in one direction 
Please help

**Comment by jazzl0ver** [comment]
i don't quite remember - more than 2 years have passed, but that seems to be expected. the motor reversing logic is implemented in the LUA script

**Comment by SarthakRobotics** [comment]
Yes right thanks for help the motor reversing was resolved by just tweeking the ranged of lua scripts.
But in case of throttle it is not switching the direction of motor as fast is it doing it in ground steering. 
Any idea what could cause that.

**Comment by jazzl0ver** [comment]
try to swap the motors. if it's not the case, you probably need to tweak the values in the script. as i told you i played with it long time ago and don't remember the details, sorry.

**Comment by SarthakRobotics** [comment]
Okay Sure i will try thank you !!
